FROM python:3.8-alpine
MAINTAINER Ivan Hahanov 'ivanhahanov13@gmail.com'
COPY app /app
WORKDIR /app
RUN pip3 install -r requirements.txt
RUN mkdir /flag{D1r3ct0ry_is_d@ng3r0us}
RUN mkdir /app/material/programming
CMD python3 app.py